# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

help_texts = {
    'lino_voga.lib.invoicing.Plan' : _("""An extended invoicing plan."""),
    'lino_voga.lib.invoicing.Plan.course' : _("""If this field is nonempty, select only enrolments of that
given course."""),
    'lino_voga.lib.invoicing.StartInvoicingForCourse' : _("""Start an invoicing plan for this course."""),
    'lino_voga.lib.voga.migrate.Migrator' : _("""This class is used because a voga Site has
ad.Site.migration_class set to
"lino_voga.migrate.Migrator"."""),
    'lino_voga.lib.voga.user_types.Teacher' : _("""Somebody who can just register presences of participants, i.e. mark
them as absent or present."""),
    'lino_voga.lib.cal.Room' : _("""Extends lino_xl.lib.cal.Room by adding one field:"""),
    'lino_voga.lib.cal.Room.fee' : _("""The default fee to pay when renting this room to an external
organization."""),
}
